### PR TITLE
demo: Update mtc.rviz to use fixed robot color + alpha

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Just a minor tweak:

Before:
> image

After:
> image

### CODE REVIEW

**Review by rhaschke — APPROVED** [review]
It's a matter of taste, but yes, this better highlights the difference between the MTC robot state and the real one.

**Comment by rhaschke** [comment]
Maybe we should introduce this setting as a default for the MTC display?

**Comment by EricCousineau-TRI** [comment]
Yeah, that'd be awesome! Where does that come in?

**Comment by rhaschke** [comment]
Here: https://github.com/ros-planning/moveit_task_constructor/blob/f99d03386ad8751fb0ade71c09a9810019a950ad/visualization/visualization_tools/src/task_solution_visualization.cpp#L115
and here: https://github.com/ros-planning/moveit_task_constructor/blob/f99d03386ad8751fb0ade71c09a9810019a950ad/visualization/visualization_tools/src/task_solution_visualization.cpp#L124

**Review by rhaschke — COMMENTED** [review]
The reason, I don't fully like this PR yet, is that the robot will remain purple-only and transparent when moving. This makes it hard to recognize details. Actually, it would be nice to just tint the original meshes.
I will leave this open to be resolved later.

**Comment by rhaschke** [comment]
Closing due to inactivity

**Pull request closed without merging**
